name: ci

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get dependencies
      - run: flutter pub get
      # - run: dart run build_runner build
      - run: flutter analyze
      - run: flutter test

  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get dependencies
      - run: flutter pub get
      - name: Build apk file
      - run: flutter build apk
      - name: Build app bundle file
      - run: flutter build appbundle
      - name: Upload the gen apk file to the specified place
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk 
        
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Get dependencies
      - run: flutter pub get
      - run: flutter test
      - name: Build ios ipa file
      - run: flutter build ios --release --no-codesign
